version: '3.8'
services:

  blog:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    restart: unless-stopped
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules:cached'
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"

